### ISSUE TITLE
help, how to ignore javascript error

### ISSUE THREAD

**Issue by fortunesusw** [phantombuster/nickjs#44]
```
> Tab 1: Page JavaScript error: ReferenceError: c is not defined
    at sendLog (https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/static/protocol/https/plugins/every_cookie_mac_82990d4.js:4:177)
    at https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/static/protocol/https/plugins/every_cookie_mac_82990d4.js:5:127
> Tab 1: Navigation (open): https://www.baidu.com/
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=he&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=2&pwd=h&cb=jQuery1102022635599116432248_1531837205312&_=1531837205315:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=hea&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=3&pwd=he&cb=jQuery1102022635599116432248_1531837205312&_=1531837205316:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=h&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=1&cb=jQuery1102022635599116432248_1531837205312&_=1531837205314:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headle&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=6&pwd=headl&cb=jQuery1102022635599116432248_1531837205312&_=1531837205319:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=9&pwd=headless&cb=jQuery1102022635599116432248_1531837205312&_=1531837205322:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headl&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=5&pwd=head&cb=jQuery1102022635599116432248_1531837205312&_=1531837205318:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=8&pwd=headles&cb=jQuery1102022635599116432248_1531837205312&_=1531837205321:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=head&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=4&pwd=hea&cb=jQuery1102022635599116432248_1531837205312&_=1531837205317:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headles&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=7&pwd=headle&cb=jQuery1102022635599116432248_1531837205312&_=1531837205320:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20c&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=10&pwd=headless%20&cb=jQuery1102022635599116432248_1531837205312&_=1531837205323:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20ch&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=11&pwd=headless%20c&cb=jQuery1102022635599116432248_1531837205312&_=1531837205324:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20chro&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=13&pwd=headless%20chr&cb=jQuery1102022635599116432248_1531837205312&_=1531837205326:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20chr&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=12&pwd=headless%20ch&cb=jQuery1102022635599116432248_1531837205312&_=1531837205325:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20chrom&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=14&pwd=headless%20chro&cb=jQuery1102022635599116432248_1531837205312&_=1531837205327:1:1
> Tab 1: Page JavaScript error: TypeError: jQuery1102022635599116432248_1531837205312 is not a function
    at https://sp0.baidu.com/5a1Fazu8AA54nxGko9WTAnF6hhy/su?wd=headless%20chrome&json=1&p=3&sid=1423_21122_26350_26810&req=2&csor=15&pwd=headless%20chrom&cb=jQuery1102022635599116432248_1531837205312&_=1531837205328:1:1
```

**Comment by paps** [comment]
Set `printPageErrors` option to `false` in Nick's constructor. See https://hub.phantombuster.com/v1/reference#nick for complete documentation

**Comment by fortunesusw** [comment]
thanks very much, it works
