### ISSUE TITLE
Cannot open two node instances

### ISSUE THREAD

**Issue by gpayo** [phantombuster/nickjs#55]
I've created a Nodejs script to scrap out affiliates. When I run the script for the first time it goes ok.
The problem is when I try to run the second as it finishes with this error:
```
Error: cannot do this while another tab method is already running, each tab can execute only one action at a time
    at Tab._callToTabDriver (/home/gpayo/node_modules/nickjs/lib/es8/Tab.js:50:10)
    at Tab.getUrl (/home/gpayo/node_modules/nickjs/lib/es8/Tab.js:232:15)
    at module.exports.getItem (/home/gpayo/Dropbox/Proyectos/bebup/misc/scrapper.core.js:13:34)
    at /home/gpayo/Dropbox/Proyectos/bebup/misc/scrapper.nick.js:81:35
    at <anonymous>
```
`nick.newTab` runs ok, I can `open()` a new URL *but* when I want to execute `getURL()` it fails.

**Comment by gpayo** [comment]
Nah, it was my own mistake: nickjs works as perfect as it can be...
