### ISSUE TITLE
could not list chrome tabs: Error: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by msaus** [phantombuster/nickjs#61]
I often get this error after running for while.
Also, when I get this error, I have to restart the process.

Do you have any suggestion for this?

Google Chrome 70.0.3538.110

**Comment by paps** [comment]
Maybe you have too many open tabs? Are you closing the tabs you're not using?

"After running for a while" means about how long?

**Comment by msaus** [comment]
I always close the tab.
After crawling 10 web site, I get this error message.

**Comment by paps** [comment]
Does it happen on other websites? Is the website so heavy that maybe you have no memory left? What have to tried? Thx

**Comment by msaus** [comment]
No it dose not happened on other website.
Then, my server has 8G memory and the memory is always 3G left as well as swap not being happened.

Also, now the error happens sometimes, not often.
This is bit weird for me.

**Comment by msaus** [comment]
Possibly, we wait and see how things go.

**Comment by paps** [comment]
Maybe start NickJS in debug mode (`debug: true` in constructor) and we can see some output showing us what's wrong

**Comment by msaus** [comment]
Sorry for late reply.
I found the reason why I was getting that error.
The error comes from waitUntilPresent() saying "Error: Error: wait until present failure: exception thrown from page: waited 3013ms but element "#myelement" still not present".

**Comment by allgrowsm** [comment]
Sorry for late reply.

I got following error message from my node server.


```
2019-12-12 12:23 : {
        "timestamp": 1576120990980.748,
        "exceptionDetails": {
                "exceptionId": 1,
                "text": "Uncaught (in promise)",
                "lineNumber": 25,
                "columnNumber": 168,
                "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                "stackTrace": {
                        "callFrames": [
                                {
                                        "functionName": "Xa",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 25,
                                        "columnNumber": 168
                                },
                                {
                                        "functionName": "f.createError",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 20,
                                        "columnNumber": 256
                                },
                                {
                                        "functionName": "",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 89,
                                        "columnNumber": 56
                                }
                        ]
                },
                "exception": {
                        "type": "object",
                        "subtype": "error",
                        "className": "Error",
                        "description": "Error: Failed to load: https://tpc.googlesyndication.com/simgad/7826562839287341183?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&rs=AOga4qm_p3pX_dDUHc9p7571LQXzbndOBQ​​​\n    at Xa (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:26:169)\n    at Ta.f.createError (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:21:257)\n    at https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:90:57",
                        "objectId": "{\"injectedScriptId\":32,\"id\":1}",
                        "preview": {
                                "type": "object",
                                "subtype": "error",
                                "description": "Error: Failed to load: https://tpc.googlesyndication.com/simgad/7826562839287341183?sqp=4sqPyQQ7QjkqNxABHQAAtEIgASgBMAk4A0DwkwlYAWBfcAKAAQGIAQGdAQAAgD-oAQGwAYCt4gS4AV_FAS2ynT4&rs=AOga4qm_p3pX_dDUHc9p7571LQXzbndOBQ​​​\n    at Xa (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:26:169)\n    at Ta.f.createError (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:21:257)\n    at https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:90:57",
                                "overflow": false,
                                "properties": [
                                        {
                                                "name": "reported",
                                                "type": "boolean",
                                                "value": "true"
                                        },
                                        {
                                                "name": "stack",
                                                "type": "string",
                                                "value": "Error: Failed to load: https://tpc.googlesyndicati…oject.org/rtv/031912050130240/amp4ads-v0.js:90:57"
                                        },
                                        {
                                                "name": "message",
                                                "type": "string",
                                                "value": "Failed to load: https://tpc.googlesyndication.com/…FAS2ynT4&rs=AOga4qm_p3pX_dDUHc9p7571LQXzbndOBQ​​​"
                                        }
                                ]
                        }
                },
                "executionContextId": 32
        }
}
```

**Comment by allgrowsm** [comment]
```
2019-12-12 12:23 : > Tab 2: Page JavaScript error: Error: Failed to load: https://tpc.googlesyndication.com/pagead/images/abg/en.png​​​
    at Xa (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:26:169)
    at Ta.f.createError (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:21:257)
    at https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:90:57
2019-12-12 12:23 : {
        "timestamp": 1576120990983.153,
        "exceptionDetails": {
                "exceptionId": 3,
                "text": "Uncaught (in promise)",
                "lineNumber": 25,
                "columnNumber": 168,
                "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                "stackTrace": {
                        "callFrames": [
                                {
                                        "functionName": "Xa",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 25,
                                        "columnNumber": 168
                                },
                                {
                                        "functionName": "f.createError",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 20,
                                        "columnNumber": 256
                                },
                                {
                                        "functionName": "",
                                        "scriptId": "456",
                                        "url": "https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js",
                                        "lineNumber": 89,
                                        "columnNumber": 56
                                }
                        ]
                },
                "exception": {
                        "type": "object",
                        "subtype": "error",
                        "className": "Error",
                        "description": "Error: Failed to load: https://tpc.googlesyndication.com/pagead/images/abg/icon.png​​​\n    at Xa (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:26:169)\n    at Ta.f.createError (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:21:257)\n    at https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:90:57",
                        "objectId": "{\"injectedScriptId\":32,\"id\":3}",
                        "preview": {
                                "type": "object",
                                "subtype": "error",
                                "description": "Error: Failed to load: https://tpc.googlesyndication.com/pagead/images/abg/icon.png​​​\n    at Xa (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:26:169)\n    at Ta.f.createError (https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:21:257)\n    at https://cdn.ampproject.org/rtv/031912050130240/amp4ads-v0.js:90:57",
                                "overflow": false,
                                "properties": [
                                        {
                                                "name": "reported",
                                                "type": "boolean",
                                                "value": "true"
                                        },
                                        {
                                                "name": "stack",
                                                "type": "string",
                                                "value": "Error: Failed to load: https://tpc.googlesyndicati…oject.org/rtv/031912050130240/amp4ads-v0.js:90:57"
                                        },
                                        {
                                                "name": "message",
                                                "type": "string",
                                                "value": "Failed to load: https://tpc.googlesyndication.com/pagead/images/abg/icon.png​​​"
                                        }
                                ]
                        }
                },
                "executionContextId": 32
        }
}
```

**Comment by allgrowsm** [comment]
Sorry for late reply.

I got following errors.


```
2019-12-12 12:28 : CHROME STDERR: [1212/122838.971585:ERROR:socket_posix.cc(145)] bind() failed: address already in use (98)
DevTools listening on ws://[::1]:9222/devtools/browser/98a1a41d-1cb9-4a6c-97e8-ca7cdb590840
2019-12-12 12:28 : > It took 103ms to start and connect to Chrome (1 tries)
2019-12-12 12:28 : Error: could not list chrome tabs: Error: connect ECONNREFUSED 127.0.0.1:9222
2019-12-12 12:28 : CHROME STDERR: 
DevTools listening on ws://127.0.0.1:9222/devtools/browser/833f02dc-74f5-484f-930e-5e5b4881d26b
2019-12-12 12:28 : > It took 256ms to start and connect to Chrome (2 tries)

```

**Comment by paps** [comment]
Well, it looks like the 9222 port is already in use on your system. Maybe you already have Chrome running with debug enabled, even though NickJS tries to start a new one?

A fix would be to disable debug mode on this other Chrome instance, or at least change the port (which is one of the cmd line options of Chrome).

**Comment by allgrowsm** [comment]
@paps 
Thanks for your reply.

I finally found the reason why I am getting these errors every time I access to my crawler.

I use pm2 for load balancing node process and port collision occurs because of multiple node process.

Dose nickJS has options for the port number?

**Comment by paps** [comment]
Oh ok, I see. That means your node instances are started with debugging enabled right?

You can use `additionalChildOptions` (array of command line parameters) to change how Chrome is started in NickJS (this only works in the latest version, please update if necessary). But I'm afraid you will not be able to change the port number this way, this is one of the hardcoded options of NickJS. You will need to free port 9222 somehow. Or submit a PR :)

**Comment by allgrowsm** [comment]
@paps 
Thanks for that.
I will take a look at that option and see if I can change port number as well as submitting PR :)

**Comment by allgrowsm** [comment]
@paps 
Hi there,
I just had quick look at your source code and I understand what the hardcoded options mean.
This sort of option should be optionally set when it is constructed or after initialized.
I will have a look at this issue after the long holiday.
Happy Holiday :)
